# Generated by Django 2.0.5 on 2018-06-01 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180601_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guia',
            name='organismo',
            field=models.PositiveIntegerField(choices=[(0, 'Gobernador'), (10, 'Secretario'), (11, 'Secretaria'), (12, 'Subsecretario'), (13, 'SubScretaria'), (21, 'Director'), (22, 'Directora'), (31, 'Coordinador'), (32, 'Coordinadora'), (99, 'Administrativo')], default=0),
        ),
        migrations.AlterField(
            model_name='tramite',
            name='organismo',
            field=models.PositiveIntegerField(choices=[(0, 'Gobernador'), (10, 'Secretario'), (11, 'Secretaria'), (12, 'Subsecretario'), (13, 'SubScretaria'), (21, 'Director'), (22, 'Directora'), (31, 'Coordinador'), (32, 'Coordinadora'), (99, 'Administrativo')], default=0),
        ),
    ]
